library(shiny)
shinyUI(pageWithSidebar(
  headerPanel("Property Investment"),
  sidebarPanel(
    h4('Property'),
    textInput('text', 'Address', value=''),
    numericInput('price', 'Price of Property ($)', 500000),
    numericInput('weekly_rent', 'Rent Weekly ($)', 600),
    h5('Costs'),
    numericInput('weekly_repayments', 'Repayments (per week)', 500),
    numericInput('water_per_quarter', 'Water (per quarter)', 100),
    numericInput('management_fees', 'Asset Management (per week)', 40)
  ),
  mainPanel(
    h4('Rental Yield (%)'),
    textOutput("rentalYield"),
    h4('Cashflow Per Week ($)'),
    textOutput("cashflow_per_week"),
    h4('Cashflow Per Year ($)'),
    textOutput("cashflow_per_year"),
    br(),
    h4('Explanation'),
    helpText("This application was created to allow investors to calculate and evaluate the potential rental yield of a property and estimate the cashflow of owning said property."),
    h5("Rental Yield"),
    helpText("Rental yield is the cash generated by your income generating assest annually as a percentage of its value. To calculate rental yield, simply enter the property's price and expected weekly rent."),
    h5("Cashflow"),
    helpText("Cash flow is the net amount of cash and cash-equivalents flowing into and out of the investment. The calcuate cashflow of owning the property, simply enter the property's costs to estimate the cashflow of owning the property.")
  )
))